/* Alaya, les trois langues : francais, anglais, italien.
   PHRASES : traduction d'une chaine entiere, c'est ce qui prime.
   TERMES  : vocabulaire de joaillerie, applique aux descriptions de piece,
             du plus long au plus court. Ecrit une fois, il vaut aussi pour
             les pieces qui seront ajoutees plus tard. */
window.ALAYA_LANGUES = {
  noms: { fr: 'Français', en: 'English', it: 'Italiano' },
  html: { fr: 'fr', en: 'en', it: 'it' },

  PHRASES: {
    en: {
      /* barre de service et entete */
      'Service client': 'Client service', 'Votre emplacement :': 'Your location:',
      'Votre emplacement': 'Your location', 'Langue': 'Language',
      'Reste du monde': 'Rest of the world', 'Belgique': 'Belgium', 'Suisse': 'Switzerland',
      'Italie': 'Italy', 'Rechercher': 'Search', 'Rendez-vous': 'Appointment', 'Panier': 'Cart',
      'Menu': 'Menu', 'Fermer le menu': 'Close menu', 'Recherche': 'Search',
      /* navigation */
      'Joaillerie': 'Fine jewelry', 'Mariages & Célébrations': 'Weddings & Celebrations',
      'Cadeaux': 'Gifts', 'La Maison': 'The House', 'Guide du Diamant': 'Diamond guide',
      'Guide du diamant': 'Diamond guide', 'Prendre rendez-vous': 'Book an appointment',
      'Bijouterie Or': 'Gold jewelry', 'Bijouterie Argent': 'Silver jewelry',
      'Collections': 'Collections', 'Les collections': 'The collections',
      'Bagues': 'Rings', 'Alliances': 'Wedding bands', 'Bracelets': 'Bracelets',
      'Colliers et pendentifs': 'Necklaces and pendants', "Boucles d'oreilles": 'Earrings',
      'Toute la collection': 'The whole collection', 'Tout voir': 'See all', 'à venir': 'coming soon',
      "L'occasion": 'The occasion', 'Fiançailles': 'Engagement', 'Bagues de fiançailles': 'Engagement rings',
      'Mariage': 'Wedding', 'Offrir': 'To give', 'Par rayon': 'By category',
      'Cadeaux pour elle': 'Gifts for her', 'Cadeaux pour lui': 'Gifts for him',
      'Cadeaux de fiançailles': 'Engagement gifts', 'Cadeaux de mariage': 'Wedding gifts',
      'Carte cadeaux': 'Gift card', 'carte cadeau': 'gift card',
      /* home */
      'Un bijou pensé avec vous.': 'A piece imagined with you.',
      "Ça commence par une conversation, pas par un catalogue. Dessiné avec vous, fabriqué à la main, fait pour durer.":
        'It starts with a conversation, not a catalogue. Drawn with you, made by hand, made to last.',
      'Bagues de fiançailles et alliances. Choisies ensemble, faites pour durer.':
        'Engagement rings and wedding bands. Chosen together, made to last.',
      'Découvrir': 'Discover', 'Lire': 'Read',
      "L'atelier sur-mesure": 'The bespoke atelier',
      "Vous arrivez avec une intention. On repart avec un dessin, puis avec votre bijou.":
        'You arrive with an intention. You leave with a drawing, then with your piece.',
      "Taille, couleur, pureté, carat. Ce qu'il faut savoir avant de choisir.":
        'Cut, colour, clarity, carat. What to know before choosing.',
      /* liste */
      'Filtrer': 'Filter', 'Voir plus': 'See more', 'Accueil': 'Home', 'Trier': 'Sort',
      'Aucune pièce ne correspond.': 'No piece matches.',
      /* fiche */
      'Variations': 'Variations', 'Monture': 'Setting', 'Choisir une monture': 'Choose a setting',
      'Taille de bague': 'Ring size', 'Taille de la bague': 'Ring size', 'Choisir une taille': 'Choose a size',
      'Pierre': 'Stone', 'Choisir une pierre': 'Choose a stone', 'Longueur': 'Length',
      'Offrir ce bijou': 'Give this piece', 'écrin, mot joint, prix masqué': 'case, note enclosed, price hidden',
      'Quelle taille choisir ?': 'Which size?', 'Ajouter au panier': 'Add to cart',
      'Ajouté au panier': 'Added to cart', 'Prix sur demande': 'Price on request',
      'Demander le prix': 'Request the price', 'Dans le détail': 'In detail',
      'Entretien': 'Care', 'Livraison': 'Delivery', 'Livraison et retours': 'Delivery and returns',
      'Retours et échanges': 'Returns and exchanges', 'Moyens de paiement': 'Payment methods',
      'Mise à taille et sur-mesure': 'Resizing and bespoke', 'Une question ?': 'A question?',
      'Contactez-nous': 'Contact us', 'contactez-nous': 'contact us', 'Nous contacter': 'Contact us',
      'Voir la pierre : le diamant': 'About the stone: the diamond',
      'Dans la même collection': 'In the same collection',
      'Référence du produit :': 'Product reference:',
      'Caratages, poids et dimensions donnés à titre indicatif.': 'Carat weights, weights and dimensions are indicative.',
      'Chaque pièce peut être mise à votre taille.': 'Every piece can be sized for you.',
      "Un doute sur la taille ? On la vérifie ensemble, à l'atelier ou à distance.":
        'Unsure about the size? We check it together, at the atelier or remotely.',
      'Une autre pierre, un autre or, un autre dessin :': 'Another stone, another gold, another drawing:',
      'prenez rendez-vous': 'book an appointment', ", on commence par une conversation.": ', we start with a conversation.',
      "Rangez votre bijou dans son écrin, à l'écart des autres pièces.": 'Keep your piece in its case, away from your other pieces.',
      'Évitez le contact avec les parfums, les crèmes et les produits ménagers.': 'Avoid contact with perfume, cream and household products.',
      "Pour le nettoyer, utilisez de l'eau tiède savonneuse et une brosse très douce, puis séchez avec un chiffon doux.":
        'To clean it, use warm soapy water and a very soft brush, then dry with a soft cloth.',
      'Vous pouvez aussi nous le confier pour un nettoyage et une vérification à l’atelier, sur':
        'You can also leave it with us for cleaning and a check at the atelier, by',
      'rendez-vous': 'appointment',
      'Chaque pièce est remise dans son écrin Alaya.': 'Every piece comes in its Alaya case.',
      'Chaque bijou est remis dans son écrin Alaya.': 'Every piece comes in its Alaya case.',
      'Les délais et les frais de livraison seront précisés dans': 'Delivery times and costs will be set out in',
      'Votre facture est envoyée par e-mail.': 'Your invoice is sent by e-mail.',
      'Par carte : Visa, Mastercard, American Express.': 'By card: Visa, Mastercard, American Express.',
      'Paiement carte authentifié et sécurisé avec 3D Secure.': 'Card payment authenticated and secured with 3D Secure.',
      'Par Apple Pay.': 'By Apple Pay.',
      "Les conditions de retour et d'échange seront précisées dans": 'Return and exchange terms will be set out in',
      'Au moment de la commande, vous pouvez joindre un mot et masquer le prix du bijou.':
        'At checkout you can enclose a note and hide the price.',
      'Un cadeau peut être échangé. Pour cela,': 'A gift can be exchanged. To do so,',
      'existe aussi, de 300 à 2 000 €.': 'also exists, from 300 to 2,000 €.', 'Une': 'A',
      'Taille': 'Size', 'Tour de doigt': 'Inner circumference', 'Diamètre': 'Diameter',
      'Diamètre en pouces': 'Diameter in inches', 'Guide des tailles': 'Size guide',
      /* panier et commande */
      'Votre panier est vide': 'Your cart is empty', 'Continuer mes achats': 'Continue shopping',
      'Retirer': 'Remove', 'Total': 'Total', 'Passer commande': 'Checkout',
      'Retour à la collection': 'Back to the collection', 'Retour au panier': 'Back to the cart',
      'Livraison & paiement': 'Delivery & payment', 'Confirmation': 'Confirmation',
      'Vos coordonnées': 'Your details', 'Prénom': 'First name', 'Nom': 'Last name',
      'E-mail': 'E-mail', 'Téléphone': 'Phone', 'Adresse': 'Address', 'Complément': 'Address line 2',
      'Code postal': 'Postal code', 'Ville': 'City', 'Pays': 'Country', 'France': 'France',
      "C'est un cadeau : écrin, mot joint, prix masqué": "It's a gift: case, note enclosed, price hidden",
      'Paiement': 'Payment', 'Payer': 'Pay', 'Modifier le panier': 'Edit the cart',
      'Votre commande': 'Your order', 'Merci.': 'Thank you.',
      "L'écrin Alaya": 'The Alaya case', 'Paiement sécurisé': 'Secure payment',
      "Prendre rendez-vous à l'atelier": 'Book an appointment at the atelier',
      'WhatsApp et téléphone :': 'WhatsApp and phone:',
      'Voir la fiche complète': 'See the full page', 'Voir le panier': 'View cart',
      'Choisir pour ajouter': 'Choose to add',
      /* pied de page */
      'Services': 'Services', 'Le catalogue': 'The catalogue', 'La maison Alaya': 'The Alaya house',
      'Informations': 'Information', 'Notre histoire': 'Our story', 'Le sur-mesure': 'Bespoke',
      'Mentions légales': 'Legal notice', 'CGV': 'Terms of sale', 'Confidentialité': 'Privacy',
      'Newsletter': 'Newsletter', "S'inscrire": 'Sign up', 'Suivez-nous': 'Follow us',
      'Voir aussi': 'See also',
      "55 bagues fabriquées à la main à l'atelier de Montmartre : solitaires, entourages, pavages, bagues dôme. Or blanc, jaune ou rose 750 ‰ ou bicolore, diamant, émeraude, rubis ou saphir. Chaque bague se met à votre taille, du 46 au 60.": '55 rings made by hand at the Montmartre atelier: solitaires, halos, pavé settings, dome rings. White, yellow or rose gold 750‰ or two-tone, diamond, emerald, ruby or sapphire. Every ring is sized for you, from 46 to 60.',
      "12 alliances fabriquées à la main : demi-alliances, tours complets, anneaux plats ou bombés. Or blanc, jaune ou rose 750 ‰, brillants sertis griffes ou rail. Elles se mettent à votre taille et se dessinent sur mesure à l'atelier.": '12 wedding bands made by hand: half-set bands, full eternity bands, flat or domed. White, yellow or rose gold 750‰, brilliants claw-set or channel-set. Sized for you, or drawn bespoke at the atelier.',
      "5 bracelets fabriqués à la main : joncs ouverts, bracelets rivière, bracelets souples. Or 750 ‰, brillants, rubis ou saphirs, fermoir boîte. La longueur se règle à votre poignet, sur rendez-vous à l'atelier.": '5 bracelets made by hand: open bangles, riviera bracelets, flexible bracelets. Gold 750‰, brilliants, rubies or sapphires, box clasp. The length is set to your wrist, by appointment at the atelier.',
      "16 colliers et pendentifs fabriqués à la main : pendentifs ronds, gouttes, cœurs, colliers rivière. Or blanc, jaune ou rose 750 ‰ sur chaîne fine, diamant, émeraude, rubis ou saphir. La longueur de chaîne se choisit avec vous.": '16 necklaces and pendants made by hand: round pendants, drops, hearts, riviera necklaces. White, yellow or rose gold 750‰ on a fine chain, diamond, emerald, ruby or sapphire. The chain length is chosen with you.',
      "21 paires de boucles d'oreilles fabriquées à la main : puces, dormeuses, créoles, pendantes. Or 750 ‰, brillants en serti clos ou sur griffes, pierres de couleur et perles. Une paire peut être dessinée sur mesure à l'atelier.": '21 pairs of earrings made by hand: studs, leverbacks, hoops, drops. Gold 750‰, bezel-set or claw-set brilliants, coloured stones and pearls. A pair can be drawn bespoke at the atelier.',
      "Bagues de fiançailles et alliances Alaya, 66 pièces fabriquées à la main à Montmartre. Solitaires, entourages, demi-alliances et tours complets, en or 750 ‰, avec la pierre de votre choix. On choisit ensemble, à l'atelier ou à distance.": 'Alaya engagement rings and wedding bands, 66 pieces made by hand in Montmartre. Solitaires, halos, half-set and full eternity bands, in gold 750‰, with the stone of your choice. We choose together, at the atelier or remotely.',
      "Offrir un bijou Alaya, ou la carte cadeau de 300 à 2 000 €. Chaque pièce part dans son écrin ; au moment de la commande, un mot peut être joint et le prix masqué.": 'Give an Alaya piece, or the gift card from 300 to 2,000 €. Every piece leaves in its case; at checkout a note can be enclosed and the price hidden.',
      "Pièces fabriquées à la main à l'atelier de Montmartre. Or blanc, jaune ou rose 750 ‰, diamant, émeraude, rubis ou saphir. Chaque bijou peut être mis à votre taille ou dessiné sur mesure, sur rendez-vous.": 'Pieces made by hand at the Montmartre atelier. White, yellow or rose gold 750‰, diamond, emerald, ruby or sapphire. Every piece can be sized for you or drawn bespoke, by appointment.',
      'Fermer': 'Close', 'Précédent': 'Previous', 'Suivant': 'Next', 'Une option': 'An option', 'à choisir avant d’ajouter au panier.': 'to choose before adding to the cart.',
      'Il manque un renseignement.': 'A field is missing.', 'Envoyer un e-mail': 'Send an e-mail', 'Du lundi au vendredi de 9h00 à 19h00.': 'Monday to Friday, 9am to 7pm.'
    },
    it: {
      'Service client': 'Servizio clienti', 'Votre emplacement :': 'La tua posizione:',
      'Votre emplacement': 'La tua posizione', 'Langue': 'Lingua',
      'Reste du monde': 'Resto del mondo', 'Belgique': 'Belgio', 'Suisse': 'Svizzera',
      'Italie': 'Italia', 'Rechercher': 'Cerca', 'Rendez-vous': 'Appuntamento', 'Panier': 'Carrello',
      'Menu': 'Menu', 'Fermer le menu': 'Chiudi il menu', 'Recherche': 'Ricerca',
      'Joaillerie': 'Alta gioielleria', 'Mariages & Célébrations': 'Matrimoni e celebrazioni',
      'Cadeaux': 'Regali', 'La Maison': 'La Maison', 'Guide du Diamant': 'Guida al diamante',
      'Guide du diamant': 'Guida al diamante', 'Prendre rendez-vous': 'Prenota un appuntamento',
      'Bijouterie Or': 'Gioielli in oro', 'Bijouterie Argent': 'Gioielli in argento',
      'Collections': 'Collezioni', 'Les collections': 'Le collezioni',
      'Bagues': 'Anelli', 'Alliances': 'Fedi', 'Bracelets': 'Bracciali',
      'Colliers et pendentifs': 'Collane e pendenti', "Boucles d'oreilles": 'Orecchini',
      'Toute la collection': 'Tutta la collezione', 'Tout voir': 'Vedi tutto', 'à venir': 'in arrivo',
      "L'occasion": "L'occasione", 'Fiançailles': 'Fidanzamento', 'Bagues de fiançailles': 'Anelli di fidanzamento',
      'Mariage': 'Matrimonio', 'Offrir': 'Regalare', 'Par rayon': 'Per categoria',
      'Cadeaux pour elle': 'Regali per lei', 'Cadeaux pour lui': 'Regali per lui',
      'Cadeaux de fiançailles': 'Regali di fidanzamento', 'Cadeaux de mariage': 'Regali di matrimonio',
      'Carte cadeaux': 'Carta regalo', 'carte cadeau': 'carta regalo',
      'Un bijou pensé avec vous.': 'Un gioiello pensato con voi.',
      "Ça commence par une conversation, pas par un catalogue. Dessiné avec vous, fabriqué à la main, fait pour durer.":
        'Comincia da una conversazione, non da un catalogo. Disegnato con voi, fatto a mano, fatto per durare.',
      'Bagues de fiançailles et alliances. Choisies ensemble, faites pour durer.':
        'Anelli di fidanzamento e fedi. Scelti insieme, fatti per durare.',
      'Découvrir': 'Scopri', 'Lire': 'Leggi',
      "L'atelier sur-mesure": 'Il laboratorio su misura',
      "Vous arrivez avec une intention. On repart avec un dessin, puis avec votre bijou.":
        'Arrivate con un desiderio. Uscite con un disegno, poi con il vostro gioiello.',
      "Taille, couleur, pureté, carat. Ce qu'il faut savoir avant de choisir.":
        'Taglio, colore, purezza, carati. Quello che serve sapere prima di scegliere.',
      'Filtrer': 'Filtra', 'Voir plus': 'Vedi altro', 'Accueil': 'Home', 'Trier': 'Ordina',
      'Aucune pièce ne correspond.': 'Nessun pezzo corrisponde.',
      'Variations': 'Varianti', 'Monture': 'Montatura', 'Choisir une monture': 'Scegli la montatura',
      'Taille de bague': "Misura dell'anello", 'Taille de la bague': "Misura dell'anello",
      'Choisir une taille': 'Scegli la misura', 'Pierre': 'Pietra', 'Choisir une pierre': 'Scegli la pietra',
      'Longueur': 'Lunghezza', 'Offrir ce bijou': 'Regalare questo gioiello',
      'écrin, mot joint, prix masqué': 'astuccio, biglietto, prezzo nascosto',
      'Quelle taille choisir ?': 'Quale misura scegliere?', 'Ajouter au panier': 'Aggiungi al carrello',
      'Ajouté au panier': 'Aggiunto al carrello', 'Prix sur demande': 'Prezzo su richiesta',
      'Demander le prix': 'Richiedi il prezzo', 'Dans le détail': 'Nel dettaglio',
      'Entretien': 'Manutenzione', 'Livraison': 'Spedizione', 'Livraison et retours': 'Spedizioni e resi',
      'Retours et échanges': 'Resi e cambi', 'Moyens de paiement': 'Metodi di pagamento',
      'Mise à taille et sur-mesure': 'Misura e su misura', 'Une question ?': 'Una domanda?',
      'Contactez-nous': 'Contattaci', 'contactez-nous': 'contattaci', 'Nous contacter': 'Contattaci',
      'Voir la pierre : le diamant': 'La pietra: il diamante',
      'Dans la même collection': 'Nella stessa collezione',
      'Référence du produit :': 'Riferimento prodotto:',
      'Caratages, poids et dimensions donnés à titre indicatif.': 'Carature, pesi e dimensioni sono indicativi.',
      'Chaque pièce peut être mise à votre taille.': 'Ogni pezzo può essere portato alla vostra misura.',
      "Un doute sur la taille ? On la vérifie ensemble, à l'atelier ou à distance.":
        'Dubbi sulla misura? La verifichiamo insieme, in laboratorio o a distanza.',
      'Une autre pierre, un autre or, un autre dessin :': "Un'altra pietra, un altro oro, un altro disegno:",
      'prenez rendez-vous': 'prenotate un appuntamento', ", on commence par une conversation.": ', si comincia da una conversazione.',
      "Rangez votre bijou dans son écrin, à l'écart des autres pièces.": 'Riponete il gioiello nel suo astuccio, lontano dagli altri pezzi.',
      'Évitez le contact avec les parfums, les crèmes et les produits ménagers.': 'Evitate il contatto con profumi, creme e detersivi.',
      "Pour le nettoyer, utilisez de l'eau tiède savonneuse et une brosse très douce, puis séchez avec un chiffon doux.":
        'Per pulirlo, usate acqua tiepida e sapone con uno spazzolino molto morbido, poi asciugate con un panno morbido.',
      'Vous pouvez aussi nous le confier pour un nettoyage et une vérification à l’atelier, sur':
        'Potete anche affidarcelo per una pulizia e un controllo in laboratorio, su',
      'rendez-vous': 'appuntamento',
      'Chaque pièce est remise dans son écrin Alaya.': 'Ogni pezzo è consegnato nel suo astuccio Alaya.',
      'Chaque bijou est remis dans son écrin Alaya.': 'Ogni gioiello è consegnato nel suo astuccio Alaya.',
      'Les délais et les frais de livraison seront précisés dans': 'Tempi e costi di spedizione saranno indicati in',
      'Votre facture est envoyée par e-mail.': 'La fattura viene inviata per e-mail.',
      'Par carte : Visa, Mastercard, American Express.': 'Con carta: Visa, Mastercard, American Express.',
      'Paiement carte authentifié et sécurisé avec 3D Secure.': 'Pagamento con carta autenticato e protetto con 3D Secure.',
      'Par Apple Pay.': 'Con Apple Pay.',
      "Les conditions de retour et d'échange seront précisées dans": 'Le condizioni di reso e cambio saranno indicate in',
      'Au moment de la commande, vous pouvez joindre un mot et masquer le prix du bijou.':
        "Al momento dell'ordine potete allegare un biglietto e nascondere il prezzo.",
      'Un cadeau peut être échangé. Pour cela,': 'Un regalo può essere cambiato. Per farlo,',
      'existe aussi, de 300 à 2 000 €.': 'esiste anche, da 300 a 2.000 €.', 'Une': 'Una',
      'Taille': 'Misura', 'Tour de doigt': 'Circonferenza', 'Diamètre': 'Diametro',
      'Diamètre en pouces': 'Diametro in pollici', 'Guide des tailles': 'Guida alle misure',
      'Votre panier est vide': 'Il carrello è vuoto', 'Continuer mes achats': 'Continua lo shopping',
      'Retirer': 'Rimuovi', 'Total': 'Totale', 'Passer commande': 'Vai alla cassa',
      'Retour à la collection': 'Torna alla collezione', 'Retour au panier': 'Torna al carrello',
      'Livraison & paiement': 'Spedizione e pagamento', 'Confirmation': 'Conferma',
      'Vos coordonnées': 'I vostri dati', 'Prénom': 'Nome', 'Nom': 'Cognome',
      'E-mail': 'E-mail', 'Téléphone': 'Telefono', 'Adresse': 'Indirizzo', 'Complément': 'Interno, scala',
      'Code postal': 'CAP', 'Ville': 'Città', 'Pays': 'Paese', 'France': 'Francia',
      "C'est un cadeau : écrin, mot joint, prix masqué": 'È un regalo: astuccio, biglietto, prezzo nascosto',
      'Paiement': 'Pagamento', 'Payer': 'Paga', 'Modifier le panier': 'Modifica il carrello',
      'Votre commande': 'Il vostro ordine', 'Merci.': 'Grazie.',
      "L'écrin Alaya": "L'astuccio Alaya", 'Paiement sécurisé': 'Pagamento sicuro',
      "Prendre rendez-vous à l'atelier": 'Prenotare un appuntamento in laboratorio',
      'WhatsApp et téléphone :': 'WhatsApp e telefono:',
      'Voir la fiche complète': 'Vedi la scheda completa', 'Voir le panier': 'Vedi il carrello',
      'Choisir pour ajouter': 'Scegli per aggiungere',
      'Services': 'Servizi', 'Le catalogue': 'Il catalogo', 'La maison Alaya': 'La maison Alaya',
      'Informations': 'Informazioni', 'Notre histoire': 'La nostra storia', 'Le sur-mesure': 'Su misura',
      'Mentions légales': 'Note legali', 'CGV': 'Condizioni di vendita', 'Confidentialité': 'Privacy',
      'Newsletter': 'Newsletter', "S'inscrire": 'Iscriviti', 'Suivez-nous': 'Seguici',
      'Voir aussi': 'Vedi anche',
      "55 bagues fabriquées à la main à l'atelier de Montmartre : solitaires, entourages, pavages, bagues dôme. Or blanc, jaune ou rose 750 ‰ ou bicolore, diamant, émeraude, rubis ou saphir. Chaque bague se met à votre taille, du 46 au 60.": "55 anelli fatti a mano nel laboratorio di Montmartre: solitari, contorni, pavé, anelli a cupola. Oro bianco, giallo o rosa 750‰ o bicolore, diamante, smeraldo, rubino o zaffiro. Ogni anello è portato alla vostra misura, dal 46 al 60.",
      "12 alliances fabriquées à la main : demi-alliances, tours complets, anneaux plats ou bombés. Or blanc, jaune ou rose 750 ‰, brillants sertis griffes ou rail. Elles se mettent à votre taille et se dessinent sur mesure à l'atelier.": '12 fedi fatte a mano: verette, veretta completa, anelli piatti o bombati. Oro bianco, giallo o rosa 750‰, brillanti a griffe o a binario. Portate alla vostra misura, o disegnate su misura in laboratorio.',
      "5 bracelets fabriqués à la main : joncs ouverts, bracelets rivière, bracelets souples. Or 750 ‰, brillants, rubis ou saphirs, fermoir boîte. La longueur se règle à votre poignet, sur rendez-vous à l'atelier.": '5 bracciali fatti a mano: bracciali rigidi aperti, riviera, morbidi. Oro 750‰, brillanti, rubini o zaffiri, chiusura a scatola. La lunghezza si regola sul vostro polso, su appuntamento in laboratorio.',
      "16 colliers et pendentifs fabriqués à la main : pendentifs ronds, gouttes, cœurs, colliers rivière. Or blanc, jaune ou rose 750 ‰ sur chaîne fine, diamant, émeraude, rubis ou saphir. La longueur de chaîne se choisit avec vous.": '16 collane e pendenti fatti a mano: pendenti rotondi, a goccia, a cuore, collane riviera. Oro bianco, giallo o rosa 750‰ su catena sottile, diamante, smeraldo, rubino o zaffiro. La lunghezza della catena si sceglie con voi.',
      "21 paires de boucles d'oreilles fabriquées à la main : puces, dormeuses, créoles, pendantes. Or 750 ‰, brillants en serti clos ou sur griffes, pierres de couleur et perles. Une paire peut être dessinée sur mesure à l'atelier.": '21 paia di orecchini fatti a mano: punti luce, monachelle, cerchi, pendenti. Oro 750‰, brillanti in castone chiuso o a griffe, pietre di colore e perle. Un paio può essere disegnato su misura in laboratorio.',
      "Bagues de fiançailles et alliances Alaya, 66 pièces fabriquées à la main à Montmartre. Solitaires, entourages, demi-alliances et tours complets, en or 750 ‰, avec la pierre de votre choix. On choisit ensemble, à l'atelier ou à distance.": 'Anelli di fidanzamento e fedi Alaya, 66 pezzi fatti a mano a Montmartre. Solitari, contorni, verette e veretta completa, in oro 750‰, con la pietra che scegliete. Si sceglie insieme, in laboratorio o a distanza.',
      "Offrir un bijou Alaya, ou la carte cadeau de 300 à 2 000 €. Chaque pièce part dans son écrin ; au moment de la commande, un mot peut être joint et le prix masqué.": "Regalare un gioiello Alaya, o la carta regalo da 300 a 2.000 €. Ogni pezzo parte nel suo astuccio; al momento dell'ordine si può allegare un biglietto e nascondere il prezzo.",
      "Pièces fabriquées à la main à l'atelier de Montmartre. Or blanc, jaune ou rose 750 ‰, diamant, émeraude, rubis ou saphir. Chaque bijou peut être mis à votre taille ou dessiné sur mesure, sur rendez-vous.": 'Pezzi fatti a mano nel laboratorio di Montmartre. Oro bianco, giallo o rosa 750‰, diamante, smeraldo, rubino o zaffiro. Ogni gioiello può essere portato alla vostra misura o disegnato su misura, su appuntamento.',
      'Fermer': 'Chiudi', 'Précédent': 'Precedente', 'Suivant': 'Successivo', 'Une option': "Un'opzione", 'à choisir avant d’ajouter au panier.': 'da scegliere prima di aggiungere al carrello.',
      'Il manque un renseignement.': 'Manca un dato.', 'Envoyer un e-mail': 'Inviare una e-mail', 'Du lundi au vendredi de 9h00 à 19h00.': 'Dal lunedì al venerdì, 9-19.'
    }
  },

  /* vocabulaire des descriptions, du plus long au plus court */
  TERMES: {
    en: [
      ['Pierre principale au choix : diamant, diamant fancy, émeraude, rubis ou saphir', 'Main stone of your choice: diamond, fancy diamond, emerald, ruby or sapphire'],
      ['Pierre principale au choix : diamant, émeraude, rubis ou saphir', 'Main stone of your choice: diamond, emerald, ruby or sapphire'],
      ['Pierre principale au choix : émeraude, rubis ou saphir', 'Main stone of your choice: emerald, ruby or sapphire'],
      ['Or blanc, jaune ou rose 750 ‰, ou bicolore', 'White, yellow or rose gold 750‰, or two-tone'],
      ['Or blanc, jaune ou rose 750 ‰', 'White, yellow or rose gold 750‰'],
      ['Peut être mise à votre taille ou dessinée sur mesure, sur rendez-vous à l’atelier', 'Can be sized for you or drawn bespoke, by appointment at the atelier'],
      ['Peut être adapté ou dessiné sur mesure, sur rendez-vous à l’atelier', 'Can be adapted or drawn bespoke, by appointment at the atelier'],
      ['Peuvent être adaptées ou dessinées sur mesure, sur rendez-vous à l’atelier', 'Can be adapted or drawn bespoke, by appointment at the atelier'],
      ['Fabriquée à la main', 'Made by hand'], ['Fabriqué à la main', 'Made by hand'], ['Fabriquées à la main', 'Made by hand'],
      ['Or blanc 750 ‰', 'White gold 750‰'], ['Or jaune 750 ‰', 'Yellow gold 750‰'], ['Or rose 750 ‰', 'Rose gold 750‰'],
      ['pierre principale', 'main stone'], ['pierres', 'stones'], ['pierre', 'stone'],
      ['Pierre taille coussin', 'Cushion-cut stone'], ['Pierre taille ovale', 'Oval-cut stone'],
      ['Pierre taille poire', 'Pear-cut stone'], ['Pierre taille émeraude', 'Emerald-cut stone'],
      ['Pierre taille radiant', 'Radiant-cut stone'], ['Pierre taille cœur', 'Heart-cut stone'],
      ['Pierre ronde', 'Round stone'], ['Rubis taille poire', 'Pear-cut ruby'],
      ['Solitaire rond de grande taille', 'Large round solitaire'], ['Solitaire rond', 'Round solitaire'],
      ['Demi-alliance', 'Half-set band'], ['Alliance tour complet', 'Full eternity band'],
      ['Alliance ouverte à deux anneaux', 'Open band with two rings'], ['Alliance bombée', 'Domed band'],
      ['Alliance sept pierres', 'Seven-stone band'], ['Alliance cinq pierres', 'Five-stone band'],
      ['Bague dôme', 'Dome ring'], ['Bague ajourée en navette', 'Openwork marquise ring'],
      ['Bague ajourée', 'Openwork ring'], ['Bague croisée à trois anneaux', 'Crossed three-band ring'],
      ['Bague à trois anneaux', 'Three-band ring'], ['Bague', 'Ring'],
      ['Pendentif rond', 'Round pendant'], ['Pendentif carré posé en losange', 'Square pendant set on the diagonal'],
      ['Pendentif carré', 'Square pendant'], ['Pendentif goutte ajourée', 'Openwork drop pendant'],
      ['Pendentif goutte', 'Drop pendant'], ['Pendentif cœur', 'Heart pendant'],
      ['Pendentif fleur', 'Flower pendant'], ['Pendentif ovale', 'Oval pendant'],
      ['Petit pendentif rond', 'Small round pendant'], ['Pendentif', 'Pendant'],
      ['Créoles ouvertes en spirale', 'Open spiral hoops'], ['Créoles ouvertes en goutte', 'Open drop hoops'],
      ['Créoles ouvertes en cercle', 'Open round hoops'], ['Créoles', 'Hoops'],
      ['Dormeuses', 'Leverback earrings'], ['Pendantes', 'Drop earrings'],
      ['Puces devant-derrière', 'Front-back studs'], ['Puces triangulaires', 'Triangular studs'],
      ['Puces carrées', 'Square studs'], ['Puces rondes', 'Round studs'], ['Puces en fleur', 'Flower studs'],
      ['Petites puces', 'Small studs'], ['Puces', 'Studs'],
      ['Collier rivière', 'Riviera necklace'], ['Collier branche', 'Branch necklace'],
      ['Bracelet rivière', 'Riviera bracelet'], ['Bracelet souple', 'Flexible bracelet'],
      ['Jonc ouvert', 'Open bangle'], ['Trilogie', 'Trilogy'], ['Cabochon en serti clos', 'Bezel-set cabochon'],
      ['en serti clos', 'bezel-set'], ['serti rail', 'channel-set'], ['sertis griffes', 'claw-set'],
      ['sertis en relief', 'raised set'], ['sur quatre griffes', 'on four claws'], ['sur six griffes', 'on six claws'],
      ['sur trois griffes', 'on three claws'], ['sur griffes', 'on claws'], ['sur crochet poli', 'on a polished hook'],
      ['entièrement pavées de brillants', 'fully pavé-set with brilliants'], ['entièrement pavée de brillants', 'fully pavé-set with brilliants'],
      ['entièrement pavées', 'fully pavé-set'], ['entièrement pavée', 'fully pavé-set'],
      ['double entourage pavé', 'double pavé surround'], ['double entourage', 'double surround'],
      ['entourage carré posé en losange', 'square surround set on the diagonal'], ['entourage carré pavé', 'pavé square surround'],
      ['entourage pavé', 'pavé surround'], ['entourage', 'surround'],
      ['entourée de brillants', 'surrounded by brilliants'], ['entouré de brillants', 'surrounded by brilliants'],
      ['entourées de brillants', 'surrounded by brilliants'], ['entouré de pierres', 'surrounded by stones'],
      ['anneau fin poli', 'fine polished band'], ['anneau fin', 'fine band'], ['anneau poli', 'polished band'],
      ['anneau pavé', 'pavé band'], ['anneau croisé poli', 'polished crossover band'], ['anneau croisé', 'crossover band'],
      ['anneau double', 'double band'], ['anneau plat poli', 'flat polished band'], ['anneau plat', 'flat band'],
      ['anneau lisse', 'smooth band'], ['anneau fendu pavé', 'pavé split band'], ['anneau très fin', 'very fine band'],
      ['anneau d’émail', 'enamel ring'], ['anneau', 'band'],
      ['sur chaîne fine', 'on a fine chain'], ['chaîne fine', 'fine chain'],
      ['fermoir boîte', 'box clasp'], ['brillant central', 'central brilliant'], ['brillants', 'brilliants'],
      ['brillant', 'brilliant'], ['pavage serré', 'close pavé'], ['pavage', 'pavé'], ['pavées', 'pavé-set'],
      ['pavée', 'pavé-set'], ['pavés', 'pavé-set'], ['pavé', 'pavé-set'],
      ['Émail bleu, rose', 'Blue, pink enamel'], ['émail', 'enamel'], ['perle grise', 'grey pearl'],
      ['en goutte', 'drop-shaped'], ['en fleur', 'flower-shaped'], ['en ligne', 'in a line'],
      ['en marquise', 'marquise-cut'], ['tête-bêche', 'head to tail'], ['dégradés', 'graduated'],
      ['montées', 'set'], ['espacés sur fil d’or', 'spaced along a gold wire'], ['sur toute la surface', 'over the whole surface'],
      ['sur anneau croisé', 'on a crossover band'], ['sur anneau fin', 'on a fine band'], ['sur anneau pavé', 'on a pavé band'],
      ['une ligne de', 'a line of'], ['deux gouttes', 'two drops'], ['trois brillants', 'three brilliants'],
      ['cinq brillants', 'five brilliants'], ['sept brillants', 'seven brilliants'],
      ['feuilles de brillants', 'leaves of brilliants'], ['fleurs de rubis', 'ruby flowers'],
      ['rubis', 'rubies'], ['saphirs', 'sapphires'], ['dimension', 'dimension'], ['total', 'total'],
      ['or', 'gold'], ['Or', 'Gold'], ['Bijou', 'Piece'], ['intérieur ajouré', 'openwork inside'],
      ['un rang de', 'one row of'], ['deux rangs de', 'two rows of'], ['trois rangs', 'three rows'],
      ['au centre', 'at the centre'], ['au choix', 'of your choice'], ['posé sur', 'set on'], ['posée sur', 'set on'],
      ['épaulée de', 'shouldered by'], ['épaulé de', 'shouldered by'], ['épaulé', 'shouldered'],
      ['ouvertes', 'open'], ['ouverte', 'open'], ['ronde', 'round'], ['rond', 'round'],
      ['alternance de poires et de brillants', 'alternating pears and brilliants'],
      ['semés de marquises et de brillants', 'scattered with marquises and brilliants'],
      ['rayonnantes', 'radiating'], ['dessinée par des lignes de brillants', 'drawn by lines of brilliants']
    ],
    it: [
      ['Pierre principale au choix : diamant, diamant fancy, émeraude, rubis ou saphir', 'Pietra principale a scelta: diamante, diamante fancy, smeraldo, rubino o zaffiro'],
      ['Pierre principale au choix : diamant, émeraude, rubis ou saphir', 'Pietra principale a scelta: diamante, smeraldo, rubino o zaffiro'],
      ['Pierre principale au choix : émeraude, rubis ou saphir', 'Pietra principale a scelta: smeraldo, rubino o zaffiro'],
      ['Or blanc, jaune ou rose 750 ‰, ou bicolore', 'Oro bianco, giallo o rosa 750‰, o bicolore'],
      ['Or blanc, jaune ou rose 750 ‰', 'Oro bianco, giallo o rosa 750‰'],
      ['Peut être mise à votre taille ou dessinée sur mesure, sur rendez-vous à l’atelier', 'Può essere portato alla vostra misura o disegnato su misura, su appuntamento in laboratorio'],
      ['Peut être adapté ou dessiné sur mesure, sur rendez-vous à l’atelier', 'Può essere adattato o disegnato su misura, su appuntamento in laboratorio'],
      ['Peuvent être adaptées ou dessinées sur mesure, sur rendez-vous à l’atelier', 'Possono essere adattati o disegnati su misura, su appuntamento in laboratorio'],
      ['Fabriquée à la main', 'Fatto a mano'], ['Fabriqué à la main', 'Fatto a mano'], ['Fabriquées à la main', 'Fatti a mano'],
      ['Or blanc 750 ‰', 'Oro bianco 750‰'], ['Or jaune 750 ‰', 'Oro giallo 750‰'], ['Or rose 750 ‰', 'Oro rosa 750‰'],
      ['pierre principale', 'pietra principale'], ['pierres', 'pietre'], ['pierre', 'pietra'],
      ['Pierre taille coussin', 'Pietra taglio cuscino'], ['Pierre taille ovale', 'Pietra taglio ovale'],
      ['Pierre taille poire', 'Pietra taglio goccia'], ['Pierre taille émeraude', 'Pietra taglio smeraldo'],
      ['Pierre taille radiant', 'Pietra taglio radiant'], ['Pierre taille cœur', 'Pietra taglio cuore'],
      ['Pierre ronde', 'Pietra rotonda'], ['Rubis taille poire', 'Rubino taglio goccia'],
      ['Solitaire rond de grande taille', 'Solitario rotondo di grande misura'], ['Solitaire rond', 'Solitario rotondo'],
      ['Demi-alliance', 'Veretta'], ['Alliance tour complet', 'Veretta completa'],
      ['Alliance ouverte à deux anneaux', 'Fede aperta a due anelli'], ['Alliance bombée', 'Fede bombata'],
      ['Alliance sept pierres', 'Fede sette pietre'], ['Alliance cinq pierres', 'Fede cinque pietre'],
      ['Bague dôme', 'Anello a cupola'], ['Bague ajourée en navette', 'Anello traforato navette'],
      ['Bague ajourée', 'Anello traforato'], ['Bague croisée à trois anneaux', 'Anello incrociato a tre anelli'],
      ['Bague à trois anneaux', 'Anello a tre anelli'], ['Bague', 'Anello'],
      ['Pendentif rond', 'Pendente rotondo'], ['Pendentif carré posé en losange', 'Pendente quadrato posato a losanga'],
      ['Pendentif carré', 'Pendente quadrato'], ['Pendentif goutte ajourée', 'Pendente a goccia traforato'],
      ['Pendentif goutte', 'Pendente a goccia'], ['Pendentif cœur', 'Pendente a cuore'],
      ['Pendentif fleur', 'Pendente a fiore'], ['Pendentif ovale', 'Pendente ovale'],
      ['Petit pendentif rond', 'Piccolo pendente rotondo'], ['Pendentif', 'Pendente'],
      ['Créoles ouvertes en spirale', 'Cerchi aperti a spirale'], ['Créoles ouvertes en goutte', 'Cerchi aperti a goccia'],
      ['Créoles ouvertes en cercle', 'Cerchi aperti'], ['Créoles', 'Cerchi'],
      ['Dormeuses', 'Orecchini a monachella'], ['Pendantes', 'Orecchini pendenti'],
      ['Puces devant-derrière', 'Punti luce davanti-dietro'], ['Puces triangulaires', 'Punti luce triangolari'],
      ['Puces carrées', 'Punti luce quadrati'], ['Puces rondes', 'Punti luce rotondi'], ['Puces en fleur', 'Punti luce a fiore'],
      ['Petites puces', 'Piccoli punti luce'], ['Puces', 'Punti luce'],
      ['Collier rivière', 'Collana riviera'], ['Collier branche', 'Collana a ramo'],
      ['Bracelet rivière', 'Bracciale riviera'], ['Bracelet souple', 'Bracciale morbido'],
      ['Jonc ouvert', 'Bracciale rigido aperto'], ['Trilogie', 'Trilogy'], ['Cabochon en serti clos', 'Cabochon in castone chiuso'],
      ['en serti clos', 'in castone chiuso'], ['serti rail', 'a binario'], ['sertis griffes', 'a griffe'],
      ['sertis en relief', 'in rilievo'], ['sur quatre griffes', 'su quattro griffe'], ['sur six griffes', 'su sei griffe'],
      ['sur trois griffes', 'su tre griffe'], ['sur griffes', 'su griffe'], ['sur crochet poli', 'su gancio lucido'],
      ['entièrement pavées de brillants', 'interamente pavé di brillanti'], ['entièrement pavée de brillants', 'interamente pavé di brillanti'],
      ['entièrement pavées', 'interamente pavé'], ['entièrement pavée', 'interamente pavé'],
      ['double entourage pavé', 'doppio contorno pavé'], ['double entourage', 'doppio contorno'],
      ['entourage carré posé en losange', 'contorno quadrato posato a losanga'], ['entourage carré pavé', 'contorno quadrato pavé'],
      ['entourage pavé', 'contorno pavé'], ['entourage', 'contorno'],
      ['entourée de brillants', 'circondata da brillanti'], ['entouré de brillants', 'circondato da brillanti'],
      ['entourées de brillants', 'circondati da brillanti'], ['entouré de pierres', 'circondato da pietre'],
      ['anneau fin poli', 'anello sottile lucido'], ['anneau fin', 'anello sottile'], ['anneau poli', 'anello lucido'],
      ['anneau pavé', 'anello pavé'], ['anneau croisé poli', 'anello incrociato lucido'], ['anneau croisé', 'anello incrociato'],
      ['anneau double', 'anello doppio'], ['anneau plat poli', 'anello piatto lucido'], ['anneau plat', 'anello piatto'],
      ['anneau lisse', 'anello liscio'], ['anneau fendu pavé', 'anello aperto pavé'], ['anneau très fin', 'anello molto sottile'],
      ['anneau d’émail', 'anello di smalto'], ['anneau', 'anello'],
      ['sur chaîne fine', 'su catena sottile'], ['chaîne fine', 'catena sottile'],
      ['fermoir boîte', 'chiusura a scatola'], ['brillant central', 'brillante centrale'], ['brillants', 'brillanti'],
      ['brillant', 'brillante'], ['pavage serré', 'pavé fitto'], ['pavage', 'pavé'], ['pavées', 'pavé'],
      ['pavée', 'pavé'], ['pavés', 'pavé'], ['pavé', 'pavé'],
      ['Émail bleu, rose', 'Smalto blu, rosa'], ['émail', 'smalto'], ['perle grise', 'perla grigia'],
      ['en goutte', 'a goccia'], ['en fleur', 'a fiore'], ['en ligne', 'in linea'],
      ['en marquise', 'taglio navette'], ['tête-bêche', 'testa a coda'], ['dégradés', 'in scalare'],
      ['montées', 'montate'], ['espacés sur fil d’or', "distanziati su filo d'oro"], ['sur toute la surface', 'su tutta la superficie'],
      ['sur anneau croisé', 'su anello incrociato'], ['sur anneau fin', 'su anello sottile'], ['sur anneau pavé', 'su anello pavé'],
      ['une ligne de', 'una linea di'], ['deux gouttes', 'due gocce'], ['trois brillants', 'tre brillanti'],
      ['cinq brillants', 'cinque brillanti'], ['sept brillants', 'sette brillanti'],
      ['feuilles de brillants', 'foglie di brillanti'], ['fleurs de rubis', 'fiori di rubini'],
      ['rubis', 'rubini'], ['saphirs', 'zaffiri'], ['dimension', 'dimensione'], ['total', 'totale'],
      ['or', 'oro'], ['Or', 'Oro'], ['Bijou', 'Gioiello'], ['intérieur ajouré', 'interno traforato'],
      ['un rang de', 'un giro di'], ['deux rangs de', 'due giri di'], ['trois rangs', 'tre giri'],
      ['au centre', 'al centro'], ['au choix', 'a scelta'], ['posé sur', 'posato su'], ['posée sur', 'posata su'],
      ['épaulée de', 'con spalle di'], ['épaulé de', 'con spalle di'], ['épaulé', 'con spalle'],
      ['ouvertes', 'aperti'], ['ouverte', 'aperto'], ['ronde', 'rotonda'], ['rond', 'rotondo'],
      ['alternance de poires et de brillants', 'alternanza di gocce e brillanti'],
      ['semés de marquises et de brillants', 'punteggiati di navette e brillanti'],
      ['rayonnantes', 'a raggiera'], ['dessinée par des lignes de brillants', 'disegnato da linee di brillanti']
    ]
  }
};
